language: ruby
rvm:
  - 2.1.0
env:
  - DB=sqlite
before_install:
  - export TESTDATA_HOST='http://testdata.player.fm'
  - gem install rake
  - bundle install
  - cd test/dummy
  #- bin/blat.sh
  - RAILS_ENV=test bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  #- bundler_args: --binstubs=./bundler_stubs
  - cd ../..
script: bundle exec rake
